services:
  cohort_management:
    command: ["sleep", "infinity"]

  db:
    image: postgres:13-alpine
    volumes:
      - db-test-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}"]

  app-tests:
    build:
      context: .
      dockerfile: backend/cohort_management/docker/Dockerfile
      args:
        INSTALL_TEST_REQUIREMENTS: "true"
    command: ["pytest", "--tb=short", "--disable-warnings", "-q"]
    environment:
      - PYTHONPATH=/cohort_management
      - ENV_STATE=test
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
      - init

  init:
    build:
      context: .
      dockerfile: backend/cohort_management/docker/init.dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}"]
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 5s

volumes:
  db-test-data: