services:
  cohort_management:
    container_name: cohort_management
    build:
      context: .
      dockerfile: backend/cohort_management/docker/Dockerfile
    ports:
      - "8001:8000"
    environment:
      - ENV_STATE=${ENV_STATE:-dev}
      - DATABASE_URL=${DATABASE_URL}
      - USERS_SECRET=${USERS_SECRET}
    depends_on:
      - db
      - init

  db:
    image: postgres:13-alpine
    volumes:
      - db-dev-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}"]

  init:
    build:
      context: .
      dockerfile: backend/cohort_management/docker/init.dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
    depends_on:
      - db

  alembic:
    container_name: alembic
    build:
      context: .
      dockerfile: backend/cohort_management/docker/Dockerfile-migration
    command: ["tail", "-f", "/dev/null"]
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - USERS_SECRET=${USERS_SECRET}
    volumes:
      - ./backend/cohort_management:/cohort_management
    depends_on:
      - db

volumes:
  db-dev-data:
