services:
  cohort_management:
    container_name: cohort_management
    build:
      context: .
      dockerfile: backend/cohort_management/docker/Dockerfile
    ports:
      - "8001:8000"
    environment:
      - ENV_STATE=${ENV_STATE:-development}
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgres/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}"]

volumes:
  dev-db-data: