version: '3'

tasks:
  start:
    desc: "Start env"
    cmds:
      - docker-compose -f docker-compose.yml --env-file ./config/.env up

  build:
    desc: "Build env"
    cmds:
      - docker-compose -f docker-compose.yml --env-file ./config/.env up --build

  build-dev:
    desc: "Build dev"
    cmds:
      - docker-compose -f docker-compose.yml --env-file ./config/.env.dev up --build

  start-dev:
    desc: "Start dev"
    cmds:
      - docker-compose -f docker-compose.yml --env-file ./config/.env.dev up

  build-test:
    desc: "Build test"
    cmds:
      - docker-compose -f docker-compose.yml -f docker-compose.test.yml --env-file ./config/.env.test up --build

  start-test:
    desc: "Start test"
    cmds:
      - docker-compose -f docker-compose.yml -f docker-compose.test.yml --env-file ./config/.env.test up

  run-tests:
    desc: "Run tests"
    cmds:
      - docker-compose -f docker-compose.yml -f docker-compose.test.yml --env-file ./config/.env.test run app-tests
