"""

Revision ID: 6bb378d9d3d3
Revises: 60041f7d7bab
Create Date: 2024-12-20 09:43:03.409592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bb378d9d3d3'
down_revision: Union[str, None] = '60041f7d7bab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=False), schema='cohort_management')
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False), schema='cohort_management')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified', schema='cohort_management')
    op.drop_column('users', 'is_superuser', schema='cohort_management')
    # ### end Alembic commands ###
