services:
  cohort_management:
    build:
      context: ../..
      args:
        - DEV=true
      dockerfile: cohort_management/docker/dockerfile
    ports:
      - "8001:8000"
    volumes:
      -../cohort_management:/cohort_management
    env_file:
      - .../config/env.${ENV_STATE:-development}
    environment:
      - ENV_STATE=${ENV_STATE:-development}
    depends_on:
      - db

db:
  image: postgres:13-alpine
  volumes:
    - dev-db-data:/var/lib/postgres/data
  environment:
    - POSTGRES_DB: ${DB_NAME}
    - POSTGRES_USER: ${DB_USER}
    - POSTGRES_PASSWORD: ${DB_PASSWORD}
  healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "devdb", "-U", "devuser"]

volumes:
  dev-db-data:
